# Generated by Django 3.1.5 on 2021-01-14 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField()),
                ('published_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('pending_review', 'Pending Review')], max_length=30)),
                ('visibility', models.BooleanField(default=True)),
                ('date_published', models.DateTimeField()),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('pitch_slam_participants', 'Pitch Slam Participants'), ('all_levels', 'All Levels'), ('general', 'General')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.URLField(blank=True, null=True)),
                ('alt', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=75, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='conference.img')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_keynote', models.BooleanField(default=False)),
                ('img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaker', to='conference.img')),
            ],
        ),
        migrations.CreateModel(
            name='SessionSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_schedules', to='conference.conferencesession')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_schedules', to='conference.sessiontopic')),
            ],
            options={
                'unique_together': {('session', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='Exhibitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exhibitors', to='conference.img')),
            ],
        ),
        migrations.AddField(
            model_name='conferencesession',
            name='related_speaker',
            field=models.ManyToManyField(to='conference.Speaker'),
        ),
        migrations.AddField(
            model_name='conferencesession',
            name='related_sponsor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='conference_sessions', to='conference.sponsor'),
        ),
        migrations.AddField(
            model_name='conferencesession',
            name='topics',
            field=models.ManyToManyField(through='conference.SessionSchedule', to='conference.SessionTopic'),
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('exhibitor', models.ManyToManyField(to='conference.Exhibitor')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferences', to='conference.conferencesession')),
                ('sponsors', models.ManyToManyField(to='conference.Sponsor')),
            ],
        ),
    ]
