# Generated by Django 3.1.5 on 2021-03-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='slug',
        ),
        migrations.AddField(
            model_name='site',
            name='folder',
            field=models.SlugField(blank=True, choices=[('codemirror', 'codemirror'), ('conference', 'conference'), ('images', 'images'), ('jqueryui', 'jqueryui'), ('novel_writers_digest_conference', 'novel_writers_digest_conference'), ('tinymce', 'tinymce'), ('writers_digest_conference', 'writers_digest_conference')], max_length=255, null=True, unique=True, verbose_name='Folder'),
        ),
    ]
