# Generated by Django 3.1.5 on 2021-01-14 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='session',
        ),
        migrations.AddField(
            model_name='conferencesession',
            name='conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conference_sessions', to='conference.conference'),
        ),
    ]
