# Generated by Django 3.1.7 on 2021-03-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_auto_20210304_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='order',
            field=models.IntegerField(default=99),
        ),
    ]
