# Generated by Django 3.1.5 on 2021-01-14 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('conference', '0002_auto_20210114_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='site',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='conferences', to='sites.site'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='speaker',
            name='img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='conference.img'),
        ),
    ]
