# Generated by Django 3.1.7 on 2021-03-11 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_menuitem_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['order', 'id']},
        ),
    ]
