# Generated by Django 3.1.5 on 2021-01-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0005_conferencecontact_faq_travel'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conferencesession',
            name='related_speaker',
            field=models.ManyToManyField(related_name='conference_sessions', to='conference.Speaker'),
        ),
    ]
