# Generated by Django 3.1.7 on 2021-04-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0005_auto_20210423_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontopic',
            name='name',
            field=models.CharField(blank=True, max_length=75, null=True, unique=True, verbose_name='Genre'),
        ),
    ]
