# Generated by Django 3.1.7 on 2021-04-23 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0006_auto_20210423_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessiontopic',
            options={'ordering': ('name',), 'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
    ]
