# Generated by Django 3.1.5 on 2021-01-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0006_auto_20210120_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='active',
            new_name='is_active',
        ),
    ]
