# Generated by Django 3.1.7 on 2021-04-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0007_auto_20210423_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='css',
            field=models.TextField(blank=True, null=True),
        ),
    ]
