# Generated by Django 3.1.5 on 2021-01-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0007_auto_20210120_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencesession',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
