# Generated by Django 3.1.7 on 2021-04-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0008_page_css'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchslam',
            name='css',
            field=models.TextField(blank=True, null=True),
        ),
    ]
