# Generated by Django 3.1.5 on 2021-01-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0008_conferencesession_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferencesession',
            name='related_sponsor',
        ),
        migrations.AddField(
            model_name='conferencesession',
            name='related_sponsor',
            field=models.ManyToManyField(related_name='conference_sessions', to='conference.Sponsor'),
        ),
    ]
