# Generated by Django 3.1.5 on 2021-01-21 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0009_auto_20210120_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferencesession',
            name='related_sponsor',
        ),
        migrations.RemoveField(
            model_name='conferencesession',
            name='topics',
        ),
        migrations.AddField(
            model_name='conferencesession',
            name='topics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conference_sessions', to='conference.sessiontopic'),
        ),
    ]
