# Generated by Django 3.1.5 on 2021-01-21 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0010_auto_20210121_1416'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionSchedule',
        ),
    ]
