# Generated by Django 3.1.5 on 2021-01-21 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0011_delete_sessionschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessiontopic',
            old_name='topic',
            new_name='name',
        ),
    ]
