# Generated by Django 3.1.5 on 2021-01-21 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0012_auto_20210121_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencesession',
            name='related_sponsor',
            field=models.ManyToManyField(blank=True, related_name='conference_sessions', to='conference.Sponsor'),
        ),
        migrations.RemoveField(
            model_name='conferencesession',
            name='topics',
        ),
        migrations.CreateModel(
            name='SessionSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_schedules', to='conference.conferencesession')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_schedules', to='conference.sessiontopic')),
            ],
            options={
                'unique_together': {('session', 'topic')},
            },
        ),
        migrations.AddField(
            model_name='conferencesession',
            name='topics',
            field=models.ManyToManyField(through='conference.SessionSchedule', to='conference.SessionTopic'),
        ),
    ]
