# Generated by Django 3.1.5 on 2021-01-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0014_auto_20210121_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencesession',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('pitch_slam_participants', 'Pitch Slam Participants'), ('all_levels', 'All Levels'), ('general', 'General')], max_length=30),
        ),
        migrations.AlterField(
            model_name='conferencesession',
            name='end_date_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='conferencesession',
            name='start_date_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='conferencesession',
            name='topics',
            field=models.ManyToManyField(related_name='conferencesessions', through='conference.SessionSchedule', to='conference.SessionTopic'),
        ),
        migrations.AlterField(
            model_name='sessiontopic',
            name='name',
            field=models.CharField(blank=True, max_length=75, null=True, unique=True),
        ),
    ]
