# Generated by Django 3.1.5 on 2021-01-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0015_auto_20210122_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencesession',
            name='end_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conferencesession',
            name='start_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
