# Generated by Django 3.1.5 on 2021-01-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0016_auto_20210122_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferencesession',
            name='end_date_time',
        ),
        migrations.RemoveField(
            model_name='conferencesession',
            name='start_date_time',
        ),
        migrations.AddField(
            model_name='sessionschedule',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionschedule',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conferencesession',
            name='related_speaker',
            field=models.ManyToManyField(blank=True, related_name='conference_sessions', to='conference.Speaker', verbose_name='Speakers'),
        ),
        migrations.AlterField(
            model_name='conferencesession',
            name='related_sponsor',
            field=models.ManyToManyField(blank=True, related_name='conference_sessions', to='conference.Sponsor', verbose_name='Sponsors'),
        ),
        migrations.AlterField(
            model_name='sessiontopic',
            name='name',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='sessionschedule',
            unique_together={('session', 'topic', 'start', 'end')},
        ),
    ]
