# Generated by Django 3.1.5 on 2021-02-02 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0017_auto_20210129_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='annual',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='novel_writers_digest_conference',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='annual',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='novel_writers_digest_conference',
        ),
        migrations.AddField(
            model_name='conferencecontact',
            name='conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conferencecontact', to='conference.conference'),
        ),
        migrations.AddField(
            model_name='faq',
            name='conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conferencfaq', to='conference.conference'),
        ),
        migrations.AddField(
            model_name='travel',
            name='conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conferenctravel', to='conference.conference'),
        ),
        migrations.CreateModel(
            name='PitchSlam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('conference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conferencpitchslam', to='conference.conference')),
            ],
        ),
    ]
