# Generated by Django 3.1.5 on 2021-02-02 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0018_auto_20210202_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conferencefaq', to='conference.conference'),
        ),
        migrations.AlterField(
            model_name='pitchslam',
            name='conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conferencepitchslam', to='conference.conference'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conferencetravel', to='conference.conference'),
        ),
    ]
