# Generated by Django 3.1.5 on 2021-02-02 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0019_auto_20210202_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchslam',
            name='pitch_imgs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pitchslam', to='conference.img'),
        ),
    ]
