# Generated by Django 3.1.5 on 2021-02-02 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0020_pitchslam_pitch_imgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='travel_imgs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel', to='conference.img'),
        ),
    ]
