# Generated by Django 3.1.5 on 2021-02-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0022_conference_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='slugify',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
