# Generated by Django 3.1.5 on 2021-02-04 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0023_speaker_slugify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speaker',
            old_name='slugify',
            new_name='slug',
        ),
    ]
