# Generated by Django 3.1.5 on 2021-02-04 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0024_auto_20210204_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='register_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('conference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conferenceregistration', to='conference.conference')),
            ],
            options={
                'unique_together': {('conference', 'registration_title', 'description', 'start', 'end')},
            },
        ),
    ]
