# Generated by Django 3.1.5 on 2021-02-04 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0025_auto_20210204_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('conference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conferenceregistration', to='conference.conference')),
            ],
            options={
                'unique_together': {('title', 'conference')},
            },
        ),
        migrations.CreateModel(
            name='RegistrationTimeFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeframes', to='conference.registrationoption')),
            ],
            options={
                'unique_together': {('registration', 'start', 'end')},
            },
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
