# Generated by Django 3.1.5 on 2021-02-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0026_auto_20210204_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='exhibitor',
            field=models.ManyToManyField(related_name='conference_exhibitor', to='conference.Exhibitor', verbose_name='Exhibitor'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='sponsors',
            field=models.ManyToManyField(related_name='conference_sponsors', to='conference.Sponsor', verbose_name='Sponsor'),
        ),
    ]
