# Generated by Django 3.1.5 on 2021-02-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0028_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='child_intro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
