# Generated by Django 3.1.5 on 2021-02-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0029_page_child_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='child_intro',
            field=models.TextField(blank=True, null=True, verbose_name='Intro for link'),
        ),
    ]
