# Generated by Django 3.1.5 on 2021-02-09 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0030_auto_20210209_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='conference.img'),
        ),
    ]
