# Generated by Django 3.1.5 on 2021-02-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0031_page_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('css', models.TextField(blank=True, null=True)),
                ('domain', models.CharField(max_length=200)),
            ],
        ),
    ]
