# Generated by Django 3.1.5 on 2021-02-09 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0032_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conferences', to='conference.site'),
        ),
    ]
