# Generated by Django 3.1.5 on 2021-02-09 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0033_auto_20210209_1117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Travel',
        ),
    ]
