# Generated by Django 3.1.5 on 2021-02-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0034_delete_travel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferencecontact',
            name='novel_writers_digest_conference',
        ),
        migrations.AddField(
            model_name='conferencecontact',
            name='novel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='site',
            name='slug',
            field=models.SlugField(blank=True, choices=[('novel_writers_digest_conference', 'novel.writersdigestconference.com'), ('writers_digest_conference', 'writersdigestconference.com')], null=True, unique=True),
        ),
    ]
