# Generated by Django 3.1.5 on 2021-02-10 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0035_auto_20210209_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speaker',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='speaker',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='slug',
            field=models.SlugField(blank=True, choices=[('conference', 'conference'), ('images', 'images'), ('novel_writers_digest_conference', 'novel_writers_digest_conference'), ('writers_digest_conference', 'writers_digest_conference')], null=True, unique=True, verbose_name='folder'),
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='conference.img')),
                ('topic', models.ManyToManyField(blank=True, null=True, related_name='agenttopic', to='conference.SessionTopic')),
            ],
        ),
    ]
