# Generated by Django 3.1.5 on 2021-02-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0036_auto_20210210_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='topic',
            field=models.ManyToManyField(blank=True, null=True, related_name='agenttopics', to='conference.SessionTopic'),
        ),
    ]
