# Generated by Django 3.1.5 on 2021-02-11 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0037_auto_20210210_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conferencesession',
            old_name='related_speaker',
            new_name='speakers',
        ),
        migrations.RenameField(
            model_name='conferencesession',
            old_name='related_sponsor',
            new_name='sponsors',
        ),
    ]
