# Generated by Django 3.1.5 on 2021-02-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0038_auto_20210211_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencesession',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
