# Generated by Django 3.1.5 on 2021-02-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0040_auto_20210212_0857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pitchslam',
            old_name='pitch_imgs',
            new_name='imgs',
        ),
    ]
