# Generated by Django 3.1.5 on 2021-02-16 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('conference', '0043_auto_20210216_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='media.image'),
        ),
        migrations.AlterField(
            model_name='exhibitor',
            name='img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exhibitors', to='media.image'),
        ),
        migrations.AlterField(
            model_name='page',
            name='img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='media.image'),
        ),
        migrations.AlterField(
            model_name='pitchslam',
            name='imgs',
            field=models.ManyToManyField(blank=True, null=True, related_name='pitchslam', to='media.Image'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='media.image'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='media.image'),
        ),
        migrations.DeleteModel(
            name='Img',
        ),
    ]
