# Generated by Django 3.1.5 on 2021-02-16 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0044_auto_20210216_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='img',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='img',
        ),
        migrations.RemoveField(
            model_name='page',
            name='img',
        ),
        migrations.RemoveField(
            model_name='pitchslam',
            name='imgs',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='img',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='img',
        ),
    ]
