# Generated by Django 3.1.5 on 2021-02-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0047_auto_20210218_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='keynote_type',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
