# Generated by Django 3.1.5 on 2021-02-23 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0048_speaker_keynote_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='conference.menuitem')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conferencemenuitem', to='conference.conference')),
            ],
        ),
    ]
