# Generated by Django 3.1.5 on 2021-02-23 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0051_menuitem_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='site',
        ),
    ]
