# Generated by Django 3.1.5 on 2021-02-23 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0052_remove_menuitem_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sitemenuitem', to='conference.site'),
        ),
    ]
