# Generated by Django 3.1.5 on 2021-02-23 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0053_menuitem_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='slug',
            new_name='link',
        ),
    ]
