# Generated by Django 3.1.5 on 2021-02-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0055_auto_20210223_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_footer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_header',
            field=models.BooleanField(default=True),
        ),
    ]
