# Generated by Django 3.1.5 on 2021-02-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0056_auto_20210224_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='agents',
            field=models.ManyToManyField(related_name='conference_agents', to='conference.Exhibitor', verbose_name='Agent'),
        ),
    ]
