# Generated by Django 3.1.5 on 2021-02-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0057_conference_agents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontopic',
            name='name',
            field=models.CharField(blank=True, max_length=75, null=True, unique=True),
        ),
    ]
