# Generated by Django 3.1.5 on 2021-02-26 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0058_auto_20210226_0853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessiontopic',
            options={'ordering': ('name',)},
        ),
    ]
