# Generated by Django 3.1.5 on 2021-02-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0060_auto_20210226_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='agents',
            field=models.ManyToManyField(related_name='conference_agents', to='conference.Agent', verbose_name='Agent'),
        ),
    ]
