# Generated by Django 3.1.5 on 2021-03-01 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0061_auto_20210226_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='topic',
            field=models.ManyToManyField(blank=True, null=True, related_name='agent_topics', to='conference.SessionTopic'),
        ),
        migrations.AlterField(
            model_name='conferenceaddon',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_AddOns', to='conference.conference'),
        ),
        migrations.AlterField(
            model_name='conferencecontact',
            name='conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conference_contact', to='conference.conference'),
        ),
        migrations.AlterField(
            model_name='conferencesession',
            name='topics',
            field=models.ManyToManyField(related_name='conference_sessions', through='conference.SessionSchedule', to='conference.SessionTopic'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conference_faq', to='conference.conference'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='site_menu_item', to='conference.site'),
        ),
        migrations.AlterField(
            model_name='pitchslam',
            name='conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conference_pitchslam', to='conference.conference'),
        ),
        migrations.AlterField(
            model_name='registrationoption',
            name='conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conference_registration', to='conference.conference'),
        ),
        migrations.AlterField(
            model_name='registrationtimeframe',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_frames', to='conference.registrationoption'),
        ),
    ]
