# Generated by Django 3.1.5 on 2021-03-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0062_auto_20210301_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontopic',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
