# Generated by Django 3.1.7 on 2021-06-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emmre_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_published',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
