# Generated by Django 3.1.5 on 2021-03-04 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingFolder',
            fields=[
                ('id', models.AutoField(db_column='id', editable=False, primary_key=True, serialize=False)),
                ('name', models.SlugField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, db_column='parent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='config.settingfolder')),
            ],
            options={
                'verbose_name': 'Setting Folder',
                'verbose_name_plural': 'Setting Folders',
                'managed': True,
                'unique_together': {('parent', 'name')},
                'order_with_respect_to': 'parent',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(db_column='id', editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=255, verbose_name='Field Title')),
                ('value', models.TextField(blank=True, null=True, verbose_name='Content Field')),
                ('type', models.CharField(blank=True, choices=[('text', 'Text'), ('boolean', 'Boolean'), ('color', 'Color'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Datetime'), ('email', 'Email'), ('image', 'Image'), ('integer', 'Integer'), ('number', 'Number'), ('phone', 'Phone'), ('url', 'Url'), ('html', 'Html'), ('javascript', 'Javascript'), ('css', 'CSS')], default=('text', 'Text'), max_length=255, null=True)),
                ('folder', models.ForeignKey(blank=True, db_column='folder', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings', to='config.settingfolder')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Settings', to='conference.site')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
                'managed': True,
                'order_with_respect_to': 'folder',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(db_column='id', editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('setting', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='config.setting')),
            ],
            options={
                'verbose_name': 'Version',
                'verbose_name_plural': 'Versions',
                'ordering': ['-created'],
                'managed': True,
                'unique_together': {('setting', 'created')},
            },
        ),
    ]
