# Generated by Django 3.1.5 on 2021-02-10 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0037_auto_20210210_1125'),
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Settings', to='conference.site'),
        ),
    ]
