# Generated by Django 3.1.5 on 2021-02-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_setting_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='key',
            field=models.SlugField(max_length=255, verbose_name='Field Title'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.TextField(blank=True, null=True, verbose_name='Content Field'),
        ),
    ]
