# Generated by Django 3.1.5 on 2021-02-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20210215_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='type',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('boolean', 'Boolean'), ('color', 'Color'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Datetime'), ('email', 'Email'), ('image', 'Image'), ('integer', 'Integer'), ('number', 'Number'), ('phone', 'Phone'), ('url', 'Url'), ('html', 'Html'), ('javascript', 'Javascript'), ('css', 'CSS')], default=('text', 'Text'), max_length=255, null=True),
        ),
    ]
