# Generated by Django 3.1.7 on 2021-06-03 11:17

from django.db import migrations, models
import media.models
import media.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('added', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(db_column='id', editable=False, primary_key=True, serialize=False)),
                ('file', models.ImageField(blank=True, null=True, storage=media.storage.S3(), upload_to=media.models.directory_path)),
                ('alt', models.CharField(blank=True, default='Blank', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['-id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('file', models.FileField(blank=True, null=True, storage=media.storage.S3(), upload_to=media.models.directory_path)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('added', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(db_column='id', editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'PDF',
                'verbose_name_plural': 'PDFs',
                'ordering': ['-id'],
                'managed': True,
            },
        ),
    ]
