# Generated by Django 3.1.5 on 2021-02-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='alt',
            field=models.CharField(blank=True, default='Blank', max_length=50, null=True),
        ),
    ]
